<?php


$createTableFoodPanda = "
	    CREATE TABLE `store_foodpanda_data` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `branch` varchar(30) DEFAULT NULL,
		  `report_date` date DEFAULT NULL,
		  `shift` varchar(20) DEFAULT NULL,
		  `time_covered` varchar(20) DEFAULT NULL,
		  `employee_name` varchar(123) DEFAULT '',
		  `supervisor` varchar(123) DEFAULT NULL,
		  `slip_no` varchar(20) DEFAULT '',
		  `category` varchar(80) DEFAULT NULL,
		  `item_name` varchar(123) DEFAULT '',
		  `item_id` int(11) DEFAULT NULL,
		  `quantity` double(11,2) DEFAULT 0.00,
		  `unit_price` double(11,2) DEFAULT 0.00,
		  `total` double(11,2) DEFAULT 0.00,
		  `remarks` longtext DEFAULT NULL,
		  `date_created` datetime DEFAULT '0000-00-00 00:00:00',
		  `date_updated` datetime DEFAULT NULL,
		  `updated_by` varchar(50) DEFAULT NULL,
		  `posted` varchar(6) DEFAULT 'No',
		  `status` varchar(6) DEFAULT 'Open',
		  `audit_mode` varchar(1) DEFAULT '0',
		  PRIMARY KEY (`id`)
	    )
	";
$createTableNavigation = "
	    CREATE TABLE `store_navigation` (
		  `id` bigint(20) NOT NULL AUTO_INCREMENT,
		  `sorting` int(6) DEFAULT 0,
		  `category_id` int(20) DEFAULT NULL,
		  `menu_name` varchar(100) DEFAULT NULL,
		  `page_name` varchar(100) DEFAULT NULL,
		  `display_icon` varchar(100) DEFAULT NULL,
		  `icon_color` varchar(100) DEFAULT NULL,
		  `table_columns` longtext DEFAULT NULL,
		  `active` int(1) DEFAULT 1,
		  PRIMARY KEY (`id`)
		)
	";

$insertThisNavigationDataToTable = [
		"INSERT INTO `store_navigation` VALUES ('1', '1', '100', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('3', '2', '100', 'Finish Goods Transfer', 'fgts', 'fa-solid fa-utensils', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('5', '3', '100', 'Transfer In/Out', 'transfer', 'fa-solid fa-right-left', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('6', '4', '100', 'Charges', 'charges', 'fa-solid fa-file-invoice-dollar', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('7', '5', '100', 'Snacks', 'snacks', 'fa-solid fa-popcorn', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('8', '6', '100', 'Bad Order', 'badorder', 'fa-solid fa-send-back', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('9', '7', '100', 'Damage', 'damage', 'fa-solid fa-wine-glass-crack', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('10', '8', '100', 'Complimentary', 'complimentary', 'fa-sharp fa-solid fa-burger-soda', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('11', '9', '100', 'Request', 'request', 'fa-solid fa-paper-plane-top', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('12', '10', '100', 'Receiving Report', 'receiving', 'fa-solid fa-inbox-in', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('13', '11', '100', 'Cash Count', 'cashcount', 'fa-solid fa-treasure-chest', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('14', '15', '1100', 'Summary Report', 'summary', 'fa-solid fa-file-spreadsheet', 'text-danger', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('15', '22', '1100', 'Submit To Server', 'submitserver', 'fa-solid fa-cloud', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('16', '1', '102', 'Receiving Report', 'rm_receiving', 'fa-solid fa-inbox-in', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('17', '2', '102', 'Transfer In/Out', 'rm_transfer', 'fa-solid fa-right-left', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('18', '4', '102', 'Phsysical Count', 'rm_pcount', 'fa-solid fa-tally', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('19', '1', '103', 'Summary Report', 'rm_summary', 'fa-solid fa-file-spreadsheet', 'text-danger', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('20', '3', '103', 'Submit To Server', 'rm_submitserver', 'fa-solid fa-cloud', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('21', '0', '102', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('22', '0', '104', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('23', '16', '1100', 'Production Report', 'production', 'fa-solid fa-hammer', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('24', '0', '103', 'Daily Usage Report', 'dum', 'fa-solid fa-fill-drip', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('26', '3', '102', 'Bad Order', 'rm_badorder', 'fa-solid fa-send-back', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('27', '13', '103', 'Production Report', 'production', 'fa-book', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('28', '12', '100', 'Frozen Dough', 'frozendough', 'fa-solid fa-icicles', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('30', '13', '100', 'Physical Count', 'pcount', 'fa-solid fa-tally', 'text-primary', '', '0')",
		"INSERT INTO `store_navigation` VALUES ('31', '14', '100', 'Store Discount', 'discount', 'fa-solid fa-tags', 'text-primary', '', '1')",
		"INSERT INTO `store_navigation` VALUES ('33', '17', '1100', 'Inventory Report', 'inventory', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('36', '1', '103', 'Inventory Report', 'rm_inventory', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('38', '0', '103', 'Production Report', 'production', 'fa-solid fa-hammer', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('39', '1', '104', 'Receiving Report', 'supplies_receiving', 'fa-solid fa-inbox-in', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('40', '2', '104', 'Transfer In/Out', 'supplies_transfer', 'fa-solid fa-right-left', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('41', '3', '104', 'Bad Order', 'supplies_badorder', 'fa-solid fa-send-back', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('42', '4', '104', 'Physical Count', 'supplies_pcount', 'fa-solid fa-tally', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('43', '5', '105', 'Summary Report', 'supplies_summary', 'fa-solid fa-file-spreadsheet', 'text-danger', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('44', '1', '106', 'Attachment Files', 'documents', 'fa-solid fa-paperclip', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('45', '0', '106', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('46', '18', '1100', 'Sales Breakdown', 'sales_breakdown', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('47', '7', '105', 'Submit To Server', 'supplies_submitserver', 'fa-solid fa-cloud', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('48', '6', '105', 'Inventory Report', 'supplies_inventory', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('49', '0', '108', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('50', '1', '108', 'Receiving Report', 'scrapinventory_receiving', 'fa-solid fa-inbox-in', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('51', '2', '108', 'Transfer In/Out', 'scrapinventory_transfer', 'fa-solid fa-right-left', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('52', '3', '108', 'Disposal', 'scrapinventory_badorder', 'fa-solid fa-send-back', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('53', '4', '108', 'Physical Count', 'scrapinventory_pcount', 'fa-solid fa-tally', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('54', '5', '109', 'Summary Report', 'scrapinventory_summary', 'fa-solid fa-file-spreadsheet', 'text-danger', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('55', '6', '109', 'Inventory Report', 'scrapinventory_inventory', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('56', '7', '109', 'Submit To Server', 'scrapinventory_submitserver', 'fa-solid fa-cloud', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('57', '0', '110', 'Dashboard', 'dashboard', 'glyphicon glyphicon-home', 'icon-color-orange', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('58', '1', '110', 'Receiving Report', 'boinventory_receiving', 'fa-solid fa-inbox-in', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('59', '2', '110', 'Transfer In/Out', 'boinventory_transfer', 'fa-solid fa-right-left', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('60', '3', '110', 'Disposal', 'boinventory_badorder', 'fa-solid fa-send-back', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('61', '4', '110', 'Physical Count', 'boinventory_pcount', 'fa-solid fa-tally', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('62', '5', '111', 'Summary Report', 'boinventory_summary', 'fa-solid fa-file-spreadsheet', 'text-danger', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('63', '6', '111', 'Inventory Report', 'boinventory_inventory', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('64', '7', '111', 'Submit To Server', 'boinventory_submitserver', 'fa-solid fa-cloud', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('65', '15', '100', 'Gcash Sales', 'gcash', 'fa-solid fa-treasure-chest', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('66', '19', '111111100', 'Sales Inv. Vs Cash Count', 'salesinv_cashcount', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('67', '16', '100', 'Grab Sales', 'grab', 'fa-solid fa-motorcycle', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('68', '18', '100', 'PAKATI', 'pakati', 'fa-solid fa-treasure-chest', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('69', '20', '1100', 'Sales Breakdown2', 'sales_breakdown2', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('70', '21', '1100', 'BO Breakdown', 'bo_breakdown', 'fa-solid fa-file-spreadsheet', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('71', '0', '200', 'Build Assembly', 'build_assembly', 'fa-solid fa-circle-bolt', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('72', '1', '200', 'Bakes`s Guide', 'bakers_guide', 'fa-solid fa-book', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('73', '2', '201', 'Submit To Server', 'ba_submitserver', 'fa-solid fa-cloud', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('74', '19', '100', 'Inventory Record', 'inventory_record', 'fa-solid fa-book', 'text-primary', null, '1')",
		"INSERT INTO `store_navigation` VALUES ('75', '17', '100', 'Food Panda', 'foodpanda', 'fa-solid fa-motorcycle', 'text-primary', null, '1');"
	];
		
